import type { Routes } from '@/core/types/routes.js'
import { generateFailedHttpResponse } from '@/core/utils/schemas.js'
import {
	login,
	getSiteInfo,
	getUserCourses,
	getAssignments,
	getCalendarEvents,
	getGrades,
	getCourseContents,
	getEnrolledUsers,
	getUserDetails,
	getCourseContext,
	getFiles,
	saveSubmission,
	submitForGrading,
} from '../handlers/index.js'
import {
	MoodleLoginBodySchema,
	MoodleTokenResponseSchema,
	MoodleSiteInfoSchema,
	MoodleCoursesResponseSchema,
	MoodleAssignmentsResponseSchema,
	MoodleEventsResponseSchema,
	MoodleGradesResponseSchema,
	MoodleCourseContentsResponseSchema,
	MoodleEnrolledUsersResponseSchema,
	MoodleUserDetailsResponseSchema,
	MoodleCourseInfoResponseSchema,
	MoodleFilesResponseSchema,
	MoodleSubmissionResponseSchema,
	MoodleTokenHeaderSchema,
	CourseIdParamsSchema,
	UserIdParamsSchema,
	AssignmentIdParamsSchema,
	CourseGradesQuerySchema,
	MoodleFilesQuerySchema,
	MoodleSaveSubmissionBodySchema,
	MoodleSubmitForGradingBodySchema,
} from '../schemas/index.js'

export const getMoodleRoutes = (): Routes => ({
	routes: [
		{
			method: 'POST',
			url: '/moodle/auth/login',
			handler: login,
			schema: {
				summary: 'Login to Moodle',
				description: 'Authenticate with Moodle and get a WebService token',
				tags: ['Moodle Auth'],
				body: MoodleLoginBodySchema,
				response: {
					200: MoodleTokenResponseSchema,
					401: generateFailedHttpResponse(401).describe('Invalid credentials'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/auth/site-info',
			handler: getSiteInfo,
			schema: {
				summary: 'Get Moodle site info',
				description: 'Get site info and current user profile from Moodle',
				tags: ['Moodle Auth'],
				headers: MoodleTokenHeaderSchema,
				response: {
					200: MoodleSiteInfoSchema,
					401: generateFailedHttpResponse(401).describe(
						'Token missing or invalid',
					),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/users/:userId/courses',
			handler: getUserCourses,
			schema: {
				summary: 'Get user courses',
				description: 'Get all courses the user is enrolled in',
				tags: ['Moodle Courses'],
				headers: MoodleTokenHeaderSchema,
				params: UserIdParamsSchema,
				response: {
					200: MoodleCoursesResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/courses/:courseId/assignments',
			handler: getAssignments,
			schema: {
				summary: 'Get course assignments',
				description: 'Get all assignments for a course',
				tags: ['Moodle Assignments'],
				headers: MoodleTokenHeaderSchema,
				params: CourseIdParamsSchema,
				response: {
					200: MoodleAssignmentsResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/courses/:courseId/events',
			handler: getCalendarEvents,
			schema: {
				summary: 'Get course calendar events',
				description: 'Get calendar events for a course',
				tags: ['Moodle Events'],
				headers: MoodleTokenHeaderSchema,
				params: CourseIdParamsSchema,
				response: {
					200: MoodleEventsResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/courses/:courseId/grades',
			handler: getGrades,
			schema: {
				summary: 'Get user grades for course',
				description: 'Get grade items for a user in a specific course',
				tags: ['Moodle Grades'],
				headers: MoodleTokenHeaderSchema,
				params: CourseIdParamsSchema,
				querystring: CourseGradesQuerySchema,
				response: {
					200: MoodleGradesResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/courses/:courseId/contents',
			handler: getCourseContents,
			schema: {
				summary: 'Get course contents',
				description: 'Get sections and modules of a course',
				tags: ['Moodle Courses'],
				headers: MoodleTokenHeaderSchema,
				params: CourseIdParamsSchema,
				response: {
					200: MoodleCourseContentsResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/courses/:courseId/enrolled-users',
			handler: getEnrolledUsers,
			schema: {
				summary: 'Get enrolled users',
				description: 'Get all enrolled users for a course',
				tags: ['Moodle Courses'],
				headers: MoodleTokenHeaderSchema,
				params: CourseIdParamsSchema,
				response: {
					200: MoodleEnrolledUsersResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/users/:userId',
			handler: getUserDetails,
			schema: {
				summary: 'Get user details',
				description: 'Get detailed user information by ID',
				tags: ['Moodle Users'],
				headers: MoodleTokenHeaderSchema,
				params: UserIdParamsSchema,
				response: {
					200: MoodleUserDetailsResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/courses/:courseId/context',
			handler: getCourseContext,
			schema: {
				summary: 'Get course context',
				description: 'Get course info with contextid for file operations',
				tags: ['Moodle Files'],
				headers: MoodleTokenHeaderSchema,
				params: CourseIdParamsSchema,
				response: {
					200: MoodleCourseInfoResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'GET',
			url: '/moodle/files',
			handler: getFiles,
			schema: {
				summary: 'Get course files',
				description: 'Get files from a Moodle course context',
				tags: ['Moodle Files'],
				headers: MoodleTokenHeaderSchema,
				querystring: MoodleFilesQuerySchema,
				response: {
					200: MoodleFilesResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'POST',
			url: '/moodle/assignments/:assignmentId/save',
			handler: saveSubmission,
			schema: {
				summary: 'Save assignment submission draft',
				description: 'Save a draft submission for an assignment',
				tags: ['Moodle Assignments'],
				headers: MoodleTokenHeaderSchema,
				params: AssignmentIdParamsSchema,
				body: MoodleSaveSubmissionBodySchema,
				response: {
					200: MoodleSubmissionResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
		{
			method: 'POST',
			url: '/moodle/assignments/:assignmentId/submit',
			handler: submitForGrading,
			schema: {
				summary: 'Submit assignment for grading',
				description: 'Submit an assignment for grading',
				tags: ['Moodle Assignments'],
				headers: MoodleTokenHeaderSchema,
				params: AssignmentIdParamsSchema,
				body: MoodleSubmitForGradingBodySchema,
				response: {
					200: MoodleSubmissionResponseSchema,
					401: generateFailedHttpResponse(401).describe('Token missing'),
					502: generateFailedHttpResponse(502).describe('Moodle API error'),
				},
			},
		},
	],
})
